import { MarketingReport, ProductInput } from '@/lib/types/marketing';
import { AIProviderInterface } from './types';

/**
 * Mock provider — returns deterministic fake data instantly.
 * Activated when MOCK_AI=true.
 */
export class MockProvider implements AIProviderInterface {
  async generateMarketingReport(input: ProductInput): Promise<MarketingReport> {
    // Simulate slight latency so loading states are visible during dev
    await new Promise((resolve) => setTimeout(resolve, 800));

    return {
      executiveSummary: `[MOCK] Executive summary for "${input.productName}". This is a placeholder generated by the mock provider. Set MOCK_AI=false and configure a real AI provider to get actual results.`,

      audiencePersona: `[MOCK] Target audience: ${input.targetAudience}. Ideal customer is tech-savvy, aged 25–40, actively looking for solutions to: "${input.problemSolved}".`,

      positioning: `[MOCK] Positioning statement: "${input.productName}" is the only ${input.category} solution that ${input.usp}. Built specifically for ${input.targetAudience}.`,

      hooks: [
        `[MOCK] Hook 1: Are you tired of ${input.problemSolved}?`,
        `[MOCK] Hook 2: Introducing ${input.productName} — finally a solution that works.`,
        `[MOCK] Hook 3: Join thousands who solved ${input.problemSolved} with us.`,
        `[MOCK] Hook 4: Stop struggling. Start winning with ${input.productName}.`,
        `[MOCK] Hook 5: ${input.usp} — that's the ${input.productName} difference.`,
      ],

      copywriting: `[MOCK] Full ad copy for ${input.productName}.\n\nWe understand the pain of ${input.problemSolved}. That's why we built ${input.productName} — a ${input.productType} solution for ${input.targetAudience}.\n\nOur unique approach: ${input.usp}.\n\nCampaign goal: ${input.campaignGoal}. Ready to start?`,

      campaignIdeas: [
        `[MOCK] Campaign 1: Instagram Reels — show the before/after of solving "${input.problemSolved}"`,
        `[MOCK] Campaign 2: Google Search Ads targeting keywords around "${input.category}"`,
        `[MOCK] Campaign 3: LinkedIn thought leadership content for "${input.targetAudience}"`,
      ],

      landingPageSuggestions: [
        `[MOCK] Hero: Bold headline addressing "${input.problemSolved}"`,
        `[MOCK] Social proof: Testimonials from ${input.targetAudience}`,
        `[MOCK] Feature section: Highlight "${input.usp}"`,
        `[MOCK] CTA: Align with campaign goal — "${input.campaignGoal}"`,
      ],

      nextActions: [
        `[MOCK] Set up analytics tracking for ${input.websiteUrl ?? 'your website'}`,
        `[MOCK] Create 3 ad variations based on the hooks above`,
        `[MOCK] Build A/B test landing page`,
        `[MOCK] Schedule first campaign launch in 7 days`,
      ],
    };
  }
}
